points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: product_taxes_rel
entity_name: null
display_name: Product Taxes Rel
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: RELATION BETWEEN product_template AND account_tax
