points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: prod_last_moved_report
entity_name: null
display_name: Prod Last Moved Report
caveats: null
active: true
entity_type: entity/GenericTable
field_order: database
description: null
