points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: pos_config_journal_rel
entity_name: null
display_name: Pos Config Journal Rel
caveats: null
active: true
entity_type: entity/GenericTable
field_order: database
description: RELATION BETWEEN pos_config AND account_journal
