points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: purchase_config_settings
entity_name: null
display_name: Purchase Config Settings
caveats: null
active: true
entity_type: entity/GenericTable
field_order: database
description: purchase.config.settings
