points_of_interest: null
preview_display: true
values: {}
settings: null
fingerprint:
  global:
    distinct-count: 2394
    nil%: 0.0
  type:
    type/Number:
      min: 1.0
      q1: 599.1110420867905
      q3: 1796.3092728754318
      max: 2394.0
      sd: 691.1410099728986
      avg: 1197.5
visibility_type: normal
base_type: type/Integer
last_analyzed: '2021-05-26T21:06:12.647719Z'
custom_position: 0
special_type: null
position: 1
fingerprint_version: 5
name: product_id
database_position: 1
has_field_values: null
display_name: Product ID
parent_id: null
caveats: null
active: true
database_type: int4
description: null
fk_target_field_id: null
