points_of_interest: null
preview_display: true
values: {}
settings: null
fingerprint:
  global:
    distinct-count: 2
    nil%: 0.0
visibility_type: normal
base_type: type/Integer
last_analyzed: '2021-05-26T21:06:12.647719Z'
custom_position: 0
special_type: type/FK
position: 2
fingerprint_version: 5
name: product_uom
database_position: 2
has_field_values: null
display_name: Product U Om
parent_id: null
caveats: null
active: true
database_type: int4
description: Unit of Measure
fk_target_field_id: /databases/Odoo/schemas/public/tables/product_uom/fields/id
