points_of_interest: null
preview_display: true
values: {}
settings: null
fingerprint:
  global:
    distinct-count: 1
    nil%: 1.0
visibility_type: normal
base_type: type/Integer
last_analyzed: '2021-05-26T21:06:12.647719Z'
custom_position: 0
special_type: type/FK
position: 31
fingerprint_version: 5
name: product_packaging
database_position: 31
has_field_values: null
display_name: Product Packaging
parent_id: null
caveats: null
active: true
database_type: int4
description: Packaging
fk_target_field_id: /databases/Odoo/schemas/public/tables/product_packaging/fields/id
