points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: product_pricelist_item
entity_name: null
display_name: Product Price List Item
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: Pricelist item
