points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: product_removal
entity_name: null
display_name: Product Removal
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: Removal Strategy
