points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: product_supplierinfo
entity_name: null
display_name: Product Supplier Info
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: Information about a product vendor
