points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: res_config_installer
entity_name: null
display_name: Res Config Installer
caveats: null
active: true
entity_type: entity/GenericTable
field_order: database
description: res.config.installer
