points_of_interest: null
preview_display: true
values: {}
settings: null
fingerprint:
  global:
    distinct-count: 2
    nil%: 0.0
  type:
    type/Number:
      min: 1.0
      q1: 1.0
      q3: 256.49176227487123
      max: 404.0
      sd: 201.5
      avg: 101.75
visibility_type: normal
base_type: type/Decimal
last_analyzed: '2021-05-26T21:06:12.647719Z'
custom_position: 0
special_type: null
position: 3
fingerprint_version: 5
name: product_uom_qty
database_position: 3
has_field_values: null
display_name: Product U Om Qt Y
parent_id: null
caveats: null
active: true
database_type: numeric
description: null
fk_target_field_id: null
