points_of_interest: null
preview_display: true
values:
  values:
  - 49
  - 2088
  - 2100
  - 2136
  human_readable_values: []
settings: null
fingerprint:
  global:
    distinct-count: 4
    nil%: 0.0
  type:
    type/Number:
      min: 49.0
      q1: 1068.5
      q3: 2118.0
      max: 2136.0
      sd: 1029.7020200038455
      avg: 1593.25
visibility_type: normal
base_type: type/Integer
last_analyzed: '2021-05-26T21:06:12.647719Z'
custom_position: 0
special_type: type/Category
position: 21
fingerprint_version: 5
name: product_tmpl_id
database_position: 21
has_field_values: auto-list
display_name: Product Tm Pl ID
parent_id: null
caveats: null
active: true
database_type: int4
description: null
fk_target_field_id: null
