points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: ir_config_parameter_groups_rel
entity_name: null
display_name: Ir Config Parameter Groups Rel
caveats: null
active: true
entity_type: entity/GenericTable
field_order: database
description: RELATION BETWEEN ir_config_parameter AND res_groups
