points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: product_putaway
entity_name: null
display_name: Product Put Away
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: Put Away Strategy
