points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: ir_config_parameter
entity_name: null
display_name: Ir Config Parameter
caveats: null
active: true
entity_type: entity/GenericTable
field_order: database
description: ir.config_parameter
