points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: account_config_settings
entity_name: null
display_name: Account Config Settings
caveats: null
active: true
entity_type: entity/UserTable
field_order: database
description: account.config.settings
