points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: account_fiscal_position_pos_config_rel
entity_name: null
display_name: Account Fiscal Position Pos Config Rel
caveats: null
active: true
entity_type: entity/UserTable
field_order: database
description: RELATION BETWEEN pos_config AND account_fiscal_position
