points_of_interest: null
preview_display: true
values: {}
settings: null
fingerprint: null
visibility_type: normal
base_type: type/Integer
last_analyzed: null
custom_position: 0
special_type: type/FK
position: 26
fingerprint_version: 0
name: product_id
database_position: 26
has_field_values: null
display_name: Product ID
parent_id: null
caveats: null
active: true
database_type: int4
description: Product
fk_target_field_id: /databases/Odoo/schemas/public/tables/product_product/fields/id
