points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: product_attribute_value_product_product_rel
entity_name: null
display_name: Product Attribute Value Product Product Rel
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: RELATION BETWEEN product_product AND product_attribute_value
