points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: pos_detail_configs
entity_name: null
display_name: Pos Detail Con Figs
caveats: null
active: true
entity_type: entity/GenericTable
field_order: database
description: RELATION BETWEEN pos_details_wizard AND pos_config
