points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: product_attribute_price
entity_name: null
display_name: Product Attribute Price
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: product.attribute.price
