points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: product_uom_categ
entity_name: null
display_name: Product U Om Cat Eg
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: Product UoM Categories
