points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: ir_values
entity_name: null
display_name: Ir Values
caveats: null
active: true
entity_type: entity/GenericTable
field_order: database
description: ir.values
