points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: product_attribute_line_product_attribute_value_rel
entity_name: null
display_name: Product Attribute Line Product Attribute Value Rel
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: RELATION BETWEEN product_attribute_line AND product_attribute_value
