points_of_interest: null
preview_display: true
values:
  values:
  - false
  - true
  human_readable_values: []
settings: null
fingerprint:
  global:
    distinct-count: 2
    nil%: 0.0
visibility_type: normal
base_type: type/Boolean
last_analyzed: '2021-05-26T21:06:12.647719Z'
custom_position: 0
special_type: type/Category
position: 4
fingerprint_version: 5
name: default
database_position: 4
has_field_values: auto-list
display_name: Default
parent_id: null
caveats: null
active: true
database_type: bool
description: Default
fk_target_field_id: null
