points_of_interest: null
visibility_type: null
schema: public
show_in_getting_started: false
name: sale_config_settings
entity_name: null
display_name: Sale Config Settings
caveats: null
active: true
entity_type: entity/TransactionTable
field_order: database
description: sale.config.settings
